const obsskin = [
    {id: 1, name: 'aeronave roxa', 
        sprite1:'./public/sources/obstacles/purplenave.png',
        rotate: true,
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 2, name: 'aeronave vermelha', 
        sprite1:'./public/sources/obstacles/rednave.png',
        rotate: true,
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 3, name: 'aeronave verde', 
        sprite1:'./public/sources/obstacles/greennave.png',
        rotate: true,
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 4, name: 'aeronave ciano', 
        sprite1:'./public/sources/obstacles/cyannave.png',
        rotate: true,
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 5, name: 'aeronave rosa', 
        sprite1:'./public/sources/obstacles/pinknave.png',
        rotate: true,
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
        {id: 6, name: 'missil', 
        sprite1:'./public/sources/obstacles/balistic1.png',
        sprite2:'./public/sources/obstacles/balistic2.png',
        sprite3:'./public/sources/obstacles/balistic3.png',
        sprite4:'./public/sources/obstacles/balistic4.png',
        colisionheigth:8,
        colisionwidth:10.4,
        heigth: 300,
        width: 110,
        bottom: -104
    },
    {id: 7, name: 'aeronave rgb', 
        sprite1:'./public/sources/obstacles/rednave.png',
        sprite2:'./public/sources/obstacles/pinknave.png',
        sprite3:'./public/sources/obstacles/purplenave.png',
        sprite4:'./public/sources/obstacles/greennave.png',
        sprite5:'./public/sources/obstacles/cyannave.png',
        rotate: true,
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 8, name: 'fusca azul', 
        sprite1:'./public/sources/obstacles/beetleblue1.png',
        sprite2:'./public/sources/obstacles/beetleblue2.png',
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 9, name: 'fusca amarelo', 
        sprite1:'./public/sources/obstacles/beetleyellow1.png',
        sprite2:'./public/sources/obstacles/beetleyellow2.png',
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 10, name: 'fusca vermelho', 
        sprite1:'./public/sources/obstacles/beetlered1.png',
        sprite2:'./public/sources/obstacles/beetlered2.png',
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
    {id: 11, name: 'fusca verde', 
        sprite1:'./public/sources/obstacles/beetlegreen1.png',
        sprite2:'./public/sources/obstacles/beetlegreen2.png',
        colisionheigth:10,
        colisionwidth:8,
        heigth: 260,
        width: 150,
        bottom: -84
    },
]